debug: false

modules:
  menuitem:
    enabled: true
  vote40:
    enabled: true
    service-name: 40Servidores
    delay-seconds: 30
  externalplaceholders:
    enabled: true

menuitem:
  slot: 8
  material: PAPER
  name: '&bMenÃº del Aventurero &7(Click Derecho)'
  lore:
  - '&7Accede al menÃº del aventurero'
  - '&7para habilidades, gestiÃ³n de protes,'
  - '&7warps, config Â¡y mÃ¡s!'
  - ''
  - '&eÂ¡Click para abrir!'
  command: dm open menu %player%
  custom-model-data: 3
  
  disabled-worlds:
  - world_koths
  - otro_mundo_ejemplo
  
  sound:
    enabled: true
    # Lista de nombres aquÃ­:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    name: BLOCK_CHEST_OPEN
    volume: 1.0
    pitch: 1.0

messages:
  prefix: '&8[&#46C3D2á´ &fUá´›ÉªÊŸs&8]&r '
  no-permission: '%prefix%&cNo tienes permiso para usar este comando.'
  only-players: '%prefix%&cSolo jugadores pueden usar este comando.'
  
  valerinutils-usage: '%prefix%&7Uso: &e/valerinutils reload'
  valerinutils-reload-ok: '%prefix%&aConfiguraciÃ³n recargada y &fmenuitem &aactualizado.'
  
  menuitem-usage: '%prefix%&7Uso: &e/menuitem &f<on|off|toggle>'
  menuitem-on: '%prefix%&aItem de menÃº &factivado&7. Ahora ocuparÃ¡ el slot configurado.'
  menuitem-off: '%prefix%&cItem de menÃº &fdesactivado&7. El slot queda libre.'
  menuitem-toggled-on: '%prefix%&aItem de menÃº &factivado&7.'
  menuitem-toggled-off: '%prefix%&cItem de menÃº &fdesactivado&7.'

joinquit:
  enabled: true
  disabled-worlds:
  - world_blacklist_example
  
  first-join:
    enabled: false
    broadcast-message:
    - '&8&m-----------------------------------------------------'
    - '&r'
    - '  <gradient:#46C3D2:white><bold>Â¡BIENVENIDO!</bold></gradient>'
    - '  &7Â¡DÃ©mosle la bienvenida a &f%player% &7al servidor!'
    - '  &7Eres el aventurero nÃºmero &f#%player_number%'
    - '&r'
    - '&8&m-----------------------------------------------------'
    title:
      enabled: false
      title: <gradient:#46C3D2:white><bold>Â¡BIENVENIDO!</bold></gradient>
      subtitle: '&7Â¡Esperamos que te diviertas!'
      fade-in: 10
      stay: 60
      fade-out: 10
    sound:
      enabled: true
      name: ENTITY_PLAYER_LEVELUP
      volume: 0.2
      pitch: 1.0
  
  join:
    # Grupos especÃ­ficos (LuckPerms)
    groups:
      # --- STAFF ---
      owner:
        priority: 100
        messages:
        - '&6ğŸŒŠ <glyph:owner> <gradient:#e03535:#651520>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 1.0
          pitch: 1.0
      admin:
        priority: 95
        messages:
        - '&6ğŸŒŠ <glyph:admin> <gradient:#ff7a40:#b02000>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 1.0
          pitch: 1.0
      mod:
        priority: 90
        messages:
        - '&6ğŸŒŠ <glyph:mod> <gradient:#ffaf20:#a03005>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 1.0
          pitch: 1.0
      helper:
        priority: 85
        messages:
        - '&6ğŸŒŠ <glyph:helper> <gradient:#50ffc5:#009985>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_AMETHYST_BLOCK_CHIME
          volume: 1.0
          pitch: 1.0
      
      # --- VIPS (Mayor a Menor) ---
      leyenda:
        priority: 60
        messages:
        - '&6ğŸŒŠ <glyph:legendary> <gradient:#ffba60:#cf4b15>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 0.5
          pitch: 2.0
      elite:
        priority: 50
        messages:
        - '&6ğŸŒŠ <glyph:elite> <#f6558e>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 0.5
          pitch: 1.5
      arcano:
        priority: 40
        messages:
        - '&6ğŸŒŠ <glyph:arcane> <#d97db3>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 0.5
          pitch: 1.0
      ascendido:
        priority: 30
        messages:
        - '&6ğŸŒŠ <glyph:ascended> <#9ce942>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 0.5
          pitch: 2.0
      guardian:
        priority: 20
        messages:
        - '&6ğŸŒŠ <glyph:guardian> <#50b5e8>%essentials_nickname%</gradient>
          &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
        sound:
          enabled: true
          name: BLOCK_NOTE_BLOCK_BELL
          volume: 0.5
          pitch: 1.0
    
    # Default (Sin rango, sin sonido)
    messages:
    - '&6ğŸŒŠ &f%player% &esá´‡ Êœá´€ á´œÉ´Éªá´…á´ &6ğŸŒŠ &8(%online%)'
    
    # Defaults deshabilitados para players normales
    title:
      enabled: false
      title: ''
      subtitle: ''
      fade-in: 10
      stay: 40
      fade-out: 10
    sound:
      enabled: false
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 1.0
    motd:
      enabled: false
      lines: []
  
  quit:
    enabled: false
    messages:
    - '&8[&c-&8] &7%player%'
    - '&8[&c-&8] &fÂ¡AdiÃ³s, %player%!'
    - '&8[&c-&8] &7%player% se ha desvanecido.'
    sound:
      enabled: false
      name: BLOCK_WOODEN_DOOR_CLOSE
      volume: 0.2
      pitch: 1.0

